### ISSUE TITLE
Question: Dirty Schedulers

### ISSUE THREAD

**Issue by alexpopov** [carlosmn/geef#10]
When this library is used, should it be used with dirty schedulers enabled so as not to wreak havoc upon the schedulers, or does the C code currently yield? 

I tried reading through the source but I couldn't find anything to confirm or deny my thoughts :( 

Thank you.

**Comment by carlosmn** [comment]
This code does neither. IIRC most of this code predates dirty schedulers being in a released version of the runtime; in either case, neither yielding or setting the schedulers are things that this project can do, as the CPU and/or IO work is performed by libgit2.

The only way to have the NIF functions return (that aren't just accessors for structs) in a timely manner to the runtime would be to run the libgit2 functions in a new thread and have that code send a message when it's completed. But that involves handling thread pools, so nobody has done it yet for this project.

**Comment by alexpopov** [comment]
Thank you for answering! We're just using `os:cmd` for now and it's working out fine (though I know it won't scale).
