### ISSUE TITLE
Can't build on Linux

### ISSUE THREAD

**Issue by ramonsnir** [carlosmn/geef#3]
Hello,

I'm trying to build geef on Arch Linux (64-bit, all packages updated). My libgit2 version is 0.22.1 and my git version is 2.3.2. My architecture is 64-bit (with Linux 3.18.6).

I ran `make` and then in the erlang shell added the code path (`/home/user/git/geef/ebin`).

When running `{ok, Repo} = geef_repo:open(".").` (or any other command), I get an error report:

```
** exception error: undefined function geef_nif:repository_open/1
     in function  geef_repo:open/1 (src/geef_repo.erl, line 39)
2> 
=ERROR REPORT==== 11-Mar-2015::19:56:10 ===
The on_load function for module geef_nif returned {error,
                                                   {load_failed,
                                                    "Failed to load NIF library: '/home/user/git/geef/priv/geef.so: undefined symbol: git_threads_init'"}}
```

Things I already know, that might help you help me:

- in `/home/user/git/geef/priv/geef.so` I see the string `git_threads_init` three times.
- in `src/geef_nif.erl, line 236` the `Dir` pattern is matched.

**Comment by carlosmn** [comment]
geef hasn't been updated in quite a while and does not support libgit2 0.22. It seems that of the functions changed, the initalization is the only thing that geef uses, so changing `git_threads_init()` to `git_libgit2_init()` and `git_threads_shutdown()` to `git_libgit2_shutdown()` should do the trick.

**Comment by ramonsnir** [comment]
Brilliant! Works!

**Comment by carlosmn** [comment]
The commit to work against v22 has been merged into master.
