### ISSUE TITLE
`Segmentation fault` when reading a commit's tree

### ISSUE THREAD

**Issue by ramonsnir** [carlosmn/geef#5]
Hello again,

I have the following Elixir test, which works, but about a third of the time leads to a segfault (after all three assertions! I tried putting debug prints). Commenting the `Commit.tree commit` line makes the segfault go away.

```elixir
{:ok, repo} = Repository.open "tmp"
{:ok, %Reference{target: commit_id}} = Reference.lookup repo, "refs/heads/master"
assert "49E7494346DCFF08279A298D1CF8F5E429FDE98D" == Base.encode16(commit_id)
{:ok, commit} = Commit.lookup repo, commit_id
assert "49E7494346DCFF08279A298D1CF8F5E429FDE98D" == Base.encode16(commit.id)
{:ok, tree} = Commit.tree commit
assert "09EC7D0E07FD6D501B7ED097E3B83C33439AB34D" == Base.encode16(tree.id)
```

The repository is a standard git 2.3.2 bare repository with a single commit with two one-character-long files.

Any idea why this happens, or how to debug this?

**Comment by ramonsnir** [comment]
When putting `printf` debug prints in `commit.c / geef_commit_tree`, none of them are reached when the program hits segfault, and all of them reach when it doesn't hit segfault.

**Comment by ramonsnir** [comment]
Calling `Commit.tree_id` and then `Tree.lookup` with the result, works just fine. I'm using that, for now, but it's weird :)

**Comment by carlosmn** [comment]
It looks like the bad line would be at https://github.com/carlosmn/geef/blob/ad9acd23568a751d85a9c2e6d5aeb7a6e74ab171/c_src/commit.c#L43 where we create a resource out of the commit object instead of the tree so the system would not know what to do about it.

**Comment by carlosmn** [comment]
Fixed in master.
